services:
  caddy:
    image: caddy:2.10.2
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - public
      - internal-life365-net
    restart: unless-stopped

networks:
  public:
    name: public
  internal-life365-net:
    name: internal-life365-net
    internal: true
